project:
  type: website
  output-dir: docs

execute:
  enabled: false

website:
  title: "ALMASTUSSIPOV"
  page-navigation: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css
    date-format: "D MMMM YYYY"
    include-in-header:
      - text: |
          <link rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
