project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - cv.qmd
    - contact.qmd

execute:
  enabled: false

website:
  title: ""
  page-navigation: false  
  navbar:
    title: ""
    left:
      - href: index.html
        text: About
      - href: cv.html
        text: CV
      - href: contact.html
        text: Contact

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css
    date-format: "D MMMM YYYY"
    include-in-header:
      - text: |
          <link rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
